### ISSUE TITLE
Site update triggers two builds

### ISSUE THREAD

**Issue by cdcasey** [crgeary/wp-jamstack-deployments#32]
Currently my settings are set to trigger builds ONLY for new / updated posts. Now whenever a post is published or updated, TWO builds are triggered. They run in sequence and both have full, successful build logs. Using Wordpress 5.3.2.

**Comment by crgeary** [comment]
I'm not sure if this is 100% correct, but I believe this is because WordPress will fire 2 actions of when a post is updated. The plugin hooks into both of these actions, and then fires off twice. You have a similar issue if you bulk edit content.

It becomes a bit more complicated if you fire off lots of changes in quick succession, in separate requests. Such as, making updates via the WP-API.

Is this causing you a problem? I'm currently working through some other stuff, so probably won't get to this until end of next week.

**Comment by cdcasey** [comment]
I'm pretty sure only one deploy was triggered until a recent update. But I don't remember if it was an update for this plugin, another plugin, or for Wordpress (or there was some other site change).

To answer your question, this is low-impact for us as we only update about once every other week. Just thought you'd like to know about the bug.

**Comment by crgeary** [comment]
Yeah, it was probably the introduction of detecting post transitions. I believe this first on status changes, and also on post update. Both can happen together, so most likely is that.

Thanks for raising. I'll get a fix out soon! 👍

**Comment by giorgioriccardi** [comment]
@crgeary has the above issue fixed?

**Comment by crgeary** [comment]
@giorgioriccardi it will be fixed today. I'll push up a fix after work to address this.

**Comment by crgeary** [comment]
Just deployed this as part of v1.0.0

**Comment by ltroya-as** [comment]
Hi, I know this issue is closed but I have the same issue on WordPress 5.7.2.

If I update only the title, it triggers once. But if I update the title and the body, it triggers the deployment twice.

Is there any workaround on this? 

Thanks in advance.

**Comment by crgeary** [comment]
@ltroya-as I would assume this is because 2 or more posts are being updated behind the scenes when you update the page content, as each one would trigger a build.

- What post types do you have configured in the plugin settings to trigger builds?
- Do you use the block editor (Gutenberg), or are you using the classic editor?
- What version of this plugin are you running?

**Comment by LTroya** [comment]
Hi @crgeary,

- Normal blog posts
- I am using Gutenberg
- 5.7.2

Let me know if I can do anything else to help you

**Comment by JuliaZamaitat** [comment]
Hi @crgeary !
I have the same problem using Wordpress 5.8.1 and deploying to Netlify with your plugin. When I create a new Post and enter a title and some description, the build hook gets triggered twice as well.

Just wondered if you found a way to prevent this?

Thank you!
