### ISSUE TITLE
Add option to support local or disable ssl verifying when using custom hooks

### ISSUE THREAD

**Issue by davistran86** [crgeary/wp-jamstack-deployments#33]
Hi, thanks a lot for this awesome plugin. I'm using this plugin to develop my gatsby web on local and test server. At the moment, I have to add the below code to WebhookTrigger.php so this plugin can trigger my custom hook. Is there anyway you can add an option so we can use custom or local hook api without adding extra code to the plugin ?.

At the beginning I did not know about this code so I thought this plugin is not working :(.

```
add_filter( 'http_request_args', function( $args ) {
   $args['reject_unsafe_urls'] = false;
   return $args;
} );
add_filter('http_request_reject_unsafe_urls','__return_false');
add_filter( 'https_local_ssl_verify', '__return_false' );
add_filter( 'https_ssl_verify', '__return_false' );
```

**Comment by crgeary** [comment]
Hey, thanks for the info.

You don't have to add that code to the deployment plugin, those are WordPress filters that can be added anywhere (in your own plugin, or in a theme) as they "hook into WordPress" at the correct points no matter where the code is added. I would recommend you move those into your own plugin or your own theme, so that they're not lost when you update the deployments plugin next. (let me know if you have questions)

I will add a checkbox to the settings page, so that you can disable this from the UI though. As I imagine other people will have this problem too.

**Comment by davistran86** [comment]
Thanks crgeary :). I'm not familiar with wordpress so I did know about this :p. I will follow your recommend :) (and hope we can get a checkbox for this too :p)
